#ifndef BATEAU_NON_TOUCHE
#define BATEAU_NON_TOUCHE 'x'
#define BATEAU_TOUCHE 'H'
#define COUP_DANS_LEAU 'o'
#endif

#ifndef SEPARATEUR
#define SEPARATEUR '|'
#endif

#ifndef NOMBRE_PORTE_AVIONS
#define NOMBRE_PORTE_AVIONS 1
#define NOMBRE_CUIRASSES 1
#define NOMBRE_CROISEURS 2
#define NOMBRE_DESTROYERS 1
#endif

